# Default values for puller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

puller:
  images:
    - busybox
  interval: 60m

app:
  image:
    repository: locnh/k8s-puller
  log:
    json: false

registry:
  username: ""
  password: ""
  server: ""